name: Sync Website

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run once a day to check if the site is up to date
  schedule:
    # Runs at 9:15 AM UTC (1:15/2:15 AM PDT)
    - cron: '15 9 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "sync"
  cancel-in-progress: true

env:
  YARN_IGNORE_ENGINES: true
  TZ: America/Los_Angeles
  # BUILD_PATH: subfolder

jobs:
  sync:
    name: Sync
    if: endsWith(github.repository, 'web-ui') != true
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commit.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Sync Project
        run: yarn sync
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit Changes
        id: commit
        run: |
          git config --global user.name "Digi"
          git config --global user.email "Digi@DigiGoat.app"
          (git commit -am "Synced website" && echo "changes=true" >> $GITHUB_OUTPUT) || echo "changes=false" >> $GITHUB_OUTPUT

      - name: Push Changes
        if: ${{ steps.commit.outputs.changes == 'true' }}
        run: git push
  deploy:
    needs: sync
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/deploy.yml
    secrets:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    with:
      changes: ${{ needs.sync.outputs.changes == 'true' }}
